# Generated by Django 5.2.5 on 2025-09-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Approved by admin to be publicly listed'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Approved by admin to be publicly visible'),
        ),
    ]
